import { Button, VerticalBox, GridBox, CheckBox, ComboBox, Switch, Spinner, LineEdit, ListView, AboutSlint, ProgressIndicator, SpinBox, HorizontalBox, StandardListView } from "std-widgets.slint";

component Splitter inherits TouchArea {
    width: 4px;
    mouse-cursor: ew-resize;

    Rectangle {
        width: 100%;
        height: 100%;
        background: blue;
    }
}

component UserInfo inherits  TouchArea {
    HorizontalBox {
        Image {}
        VerticalBox {

            Text {text: "hhhh444";}
            Text {text: "hhhh555";}
        }
        HorizontalBox {
            Text {text: "hhhh111";}
            Text {text: "hhhh222";}
            Text {text: "hhhh333";}
        }
    }
}

component RoomItemui inherits TouchArea {

    HorizontalBox {
        Image {}
        VerticalBox {
            HorizontalBox {
                Text {text: "hhhh111";}
                Text {text: "hhhh222";}
                Text {text: "hhhh333";}
            }
            Text {text: "hhhh444";}
            Text {text: "hhhh555";}
        }
    }
}

component RoomListBottom inherits TouchArea {
    HorizontalBox {
        Button {text: "fff111";}
        Button {text: "fff222";}
        Button {text: "fff333";}
        Button {text: "fff444";}
        Button {text: "fff555";}
    }
}

component MessageListHead inherits TouchArea {
    in-out property <int> msgcnt;

    HorizontalBox {
        Button {
            text: "btn111";
        }
        Text {text: "ttt呵呵222";}
        Text {text: "ttt呵呵ccc"+msgcnt;}
        Button {
            text: "btn222";
        }
        Button {
            text: "btn333";
        }
        Button {
            text: "btn444";
        }
        Button {
            text: "btn555";
        }
    }
}

component MessageListItemui inherits TouchArea {
    in-out property <string> msgtm;
    in-out property <string> msgchan;
    in-out property <string> msguser;
    in-out property <string> msgtext;

    HorizontalBox {
        Image {}
        Text {text: "ttt呵呵111";}
        Text {text: "ttt呵呵222";}
        Text {text: "ttt呵呵333";}
        Text {text: msgchan;}
        Text {text: "ttt呵呵555";}
        Image {}
    }
}

component MessageListTail inherits TouchArea {
    in-out property<string> iptval: "nam要m";
    in-out property <string> selfile;

    HorizontalBox {
        Image {}
        Image {}
        LineEdit {
            text: iptval;
        }
        Button {
            text: "btn111";
        }
        Image {}
    }
}

export component AppWindow inherits Window {
    in-out property <string> usericon;
    in-out property <string> username;
    in-out property <string> olnstatus;

    in property <[[string]]> rooms;
    in property <[string]> columns;
    in property <[[string]]> messages;

    callback justrunafunc();

    messages: [["ffff"],["gggggg"], ["hhhhhhh"], ["iiiiiii"], ["jjjjjjjj"], ["kkkkkkkk"], ["lllllllll"],["mmmmmmmm"],["nnnnnnnnnn"]];

    HorizontalBox {
        VerticalBox {
            UserInfo {

            }

            ListView {
                for v in root.messages : RoomItemui {
                    
                }
            }

            RoomListBottom {}
        }

        Splitter {}

        VerticalBox {
            MessageListHead {
                msgcnt: messages.length;
            }
            ListView {
                for v in root.messages : MessageListItemui {
                    msgchan:  v[0];
                }
            }
            MessageListTail {}
        }
    }
}

component AppWindow2 inherits Window {
    in-out property<int> counter: 42;
    in-out property<string> fdname: "nammm";

    in property <[string]> columns;
    in property <[[string]]> values;

    callback request-increase-value();
    callback justrunafunc();

    VerticalBox {
        UserInfo {}

        ListView {
            for r in  root.values :  RoomItemui{}
        }
        

        Text {
            text: "Counter: \{root.counter}";
        }
        Button {
            text: "Increase value";
            clicked => {
                root.request-increase-value();
            }
        }
        Text {
            text: "Counter: \{root.fdname}";
        }
        Button {
            text: "justrunafunc";
            clicked => {
                root.justrunafunc();
            }
        }
        Path { }
        ListView { }


        GridBox {
            
            CheckBox {
                text: "CheckBox";
            }
            ComboBox {
                model: ["first", "second", "third"];
            }
            Button {
                text: "Button";
            }
            Switch {
                text: "Switch";
            }
            Spinner { }
            LineEdit {
                text: "LineEdi拖拖拉拉";
            }
   

            ProgressIndicator { }
        }

        splitter1 := Splitter {
            x: root.width - self.width;
            height: 100%;
    
            moved => {
                self.x = min(root.width - self.width, max(400px, self.x + self.mouse-x - self.pressed-x));
            }
        }
    }
    
}
