import { Button, VerticalBox, GridBox, CheckBox, ComboBox, Switch, Spinner, LineEdit, ListView, AboutSlint, ProgressIndicator, SpinBox, HorizontalBox, StandardListView, TabWidget, GroupBox, StandardButton, TextEdit, StandardTableView } from "std-widgets.slint";


export struct GroupchatUist {
    gcid : string,
    name : string,
    icopath: string,
    lastmsg: string,
    ctmstr: string,
    author: string,
    val1 : string,
    val2 : string,
    val3 : string,
    val4 : string,
    val5 : string,
}

export struct MessageUist {
    uid : string,
    title : string,
    body : string,
    ctmstr : string,
    snder : string,
    chname : string,
    icopath : string,
    msgfmt : string,
    val1 : string,
    val2 : string,
    val3 : string,
    val4 : string,
    val5 : string,
}

export global varfn {
    in-out property <string> usericon;
    in-out property <string> username;
    in-out property <string> olnstatus;

    in-out property < [[string]]> rooms;
    in-out property < [[string]]> messages;

    in-out property <int> isandroid : 0; 
    // pure callback isandroid() -> int;
    in property <string> curpage: "none";
}

component Splitter inherits TouchArea {
    width: 4px;
    mouse-cursor: ew-resize;

    padding: 0px;
    Rectangle {
        padding: 0px;
        width: 100%;
        height: 100%;
        background: blue;
    }
}
component HSpacer inherits Rectangle {
    max-height: 1px;
    // width: 100%;
    // horizontal-stretch: 1;
}
component VSpacer inherits Rectangle {
    max-width: 1px;
    // vertical-stretch: 1;
}


component UserInfoui inherits  Rectangle {
    padding: 0px;
    HorizontalLayout {
        padding: 0px;
        Image {
            max-width: 22px;
            max-height: 22px;
            min-width: 22px;
            vertical-alignment: top;
            // source: @image-url("/home/mememe/Downloads/favicon.png");
            // source: @image-url("");
            source: @image-url("../images/border-diamonds.png");
            // image-fit: fill;
        }
        VerticalLayout {
            // padding: 0px;
            Text {text: "hhhh444";
                // padding: 0;
                vertical-alignment: center;
            }
            Text {text: "hhhh555";
                font-size: 10px; opacity: 0.5;
                // padding: 0;
                // max-height: 19px;
                vertical-alignment: top;
            }
        }
        // HorizontalBox {
            // padding: 0px;
            // Text {text: "hhhh111";}
            TextInput {text: "......"; wrap: word-wrap;}
            Button {text: ">>";}
            Button {text: "+";}
            // StandardButton {}
            // Text {text: "hhhh333";}
        // }
    }
}

component RoomItemui inherits TouchArea {
    in-out property <GroupchatUist> gcrec;

    padding: 0px;
    
    HorizontalLayout {
        padding: 0px;
        Text {
            text: "!\n!"; 
            max-width: 2px;
        }
        Image {
            padding: 0px;
            // colorize: #3016d6;
            max-height: 22px;
            max-width: 22px;
            min-width: 22px;
            vertical-alignment: top;

            // error: Cannot find image file https:
            // source: @image-url("https://interactive-examples.mdn.mozilla.net/media/examples/border-diamonds.png");
            // 添加这个属性，直接文件大小+10M???
            // source: @image-url("/home/mememe/Downloads/border-diamonds.png");
            // source: @image-url("");
            source: @image-url("../images/favicon.png");
        }
        VerticalLayout {
            padding: 0px;
           
            // Text {text: "|\n|\n|";}
            // LineEdit {
            //     // max-height: 16px;
            //     visible: false;
            // }
            HorizontalLayout {
                padding: 0px;
                Text {text: gcrec.name;}
                Text {text: gcrec.author;}
                Text {text: gcrec.ctmstr;}
            }
            Text {text: gcrec.gcid;}
            Text {text: gcrec.lastmsg;}
        }
        Text {
            text: "!\n!"; 
            max-width: 2px;
        }
    }
}

component RoomListBottomui inherits Rectangle {
    padding: 0px;

    HorizontalLayout {
        padding: 0px;

        Button {text: "fff111";}
        Button {text: "fff222";}
        Button {text: "fff333";}
        Button {text: "fff444";}
        // Button {text: "fff555";}
    }
}

component MessageListHeadui inherits Rectangle {
    in-out property <int> msgcnt;

    padding: 0px;
    HorizontalLayout {
        padding: 0px;

        Button {
            text: "btn111";
        }
        Text {text: "ttt呵呵222";}
        Text {text: "ttt呵呵ccc"+msgcnt;}
        Button {
            text: "btn222";
        }
        // Button {
        //     text: "btn333";
        // }
    }
}

component MessageListItemui inherits Rectangle {
    in-out property <string> msgtm;
    in-out property <string> msgchan;
    in-out property <string> msguser;
    in-out property <string> msgtext;

    // background: #743734;
    padding: 0px;
    HorizontalLayout {
        padding: 0px;

        Text {
            text: "!\n!"; 
            max-width: 3px;
        }
        Image {
            max-width: 22px;
            max-height: 22px;
            min-width: 22px;
            vertical-alignment: top;
            // source: @image-url("/home/mememe/Downloads/favicon.png");
            // source: @image-url("");
            source: @image-url("../images/border-diamonds.png");
            // image-fit: fill;
        }
        VerticalLayout {
            HorizontalLayout {
                Text {text: "ttt呵呵222";
                // horizontal-alignment: left;
                }
                Text {text: "ttt呵呵333";
                    // horizontal-alignment: left;
                }
                Text {text: msgchan;
                    // horizontal-alignment: left;
                }
            }

            // 这个TextInput占更小
            // TextInput {}
            // LineEdit {}
            Text {
                wrap: word-wrap;

                text: "ddttt呵呵111ddttt呵呵111 ddttt呵呵111ddttt呵呵111ddttt呵呵111ddttt呵呵111ddttt呵呵111ddttt呵呵111ddttt 呵呵111ddttt呵呵111ddttt呵呵111ddttt呵呵111ddttt呵呵111ddttt呵呵111ddttt 呵呵111ddttt呵呵111ddttt呵呵111ddttt呵呵111ddttt呵呵111ddttt呵呵111ddttt呵呵111";
                

                // horizontal-alignment: left;
            }

            Text {text: "tttvxt呵呵555";
                // horizontal-alignment: left;
            }
        }


        Image {
            max-width: 22px;
            min-width: 22px;
            vertical-alignment: top;
            source: @image-url("../images/favicon.png");
        }
        Text {
            text: "!\n!"; 
            max-width: 2px;
        }
    }
}

component MessageListTailui inherits Rectangle {
    in-out property<string> iptval: "nam要m";
    in-out property <string> selfile;

    padding: 0px;
    HorizontalBox {
        padding: 0px;
        Image {
            max-width: 22px;
            max-height: 22px;
        }
        Image {
            
            max-width: 22px;
            max-height: 22px;
            min-width: 22px;
            // vertical-alignment: top;
            source: @image-url("../images/favicon.png");
        }
        Image {
            
            max-width: 22px;
            max-height: 22px;
            min-width: 22px;
            // vertical-alignment: top;
            source: @image-url("../images/favicon.png");
        }
        // LineEdit {
        //     text: iptval;
        // }
        TextEdit {
            padding: 0px;
            // viewport-x: 0px;
            wrap: word-wrap;
            min-height: 50px;
        
            text: "ffff 欧文 烩 owef \n烟消云散汉为";

        }
        Button {
            text: "btn111";
        }
        Image {
            max-width: 22px;
            max-height: 22px;
            min-width: 22px;
            source: @image-url("../images/favicon.png");
        }
    }
}

component RoomListAndUserInfoui inherits Rectangle {
    // in-out property <[[string]]> rooms;
    in-out property <[GroupchatUist]> rooms2;
    // rooms: [["ffff"],["gggggg"], ["hhhhhhh"], ["iiiiiii"], ["jjjjjjjj"], ["kkkkkkkk"], ["lllllllll"],["mmmmmmmm"],["nnnnnnnnnn"]];


    padding: 0px;
        VerticalLayout {
            padding: 0px;

            // LineEdit {}

            UserInfoui {}

            ListView {
                padding: 0px;
                // for v in root.rooms : 
                //      RoomItemui {}
                for v in root.rooms2 :
                    RoomItemui {
                        gcrec: v;
                    }
            }

            RoomListBottomui {}
            TextInput {text: "deeemoooo";}
        }
}


// macos cupertino, android material, other fluent
// cosmic 还可以，看看不能用在android上。
// slint的 material 是设计的最差的。
// material的 padding 很大，需要调整为0px

export component AppWindow inherits Window {
    in-out property <string> usericon;
    in-out property <string> username;
    in-out property <string> olnstatus;

    in-out property <[[string]]> rooms : [];
    in-out property <[string]> columns ;
    in-out property <[[string]]> messages ;
    in-out property <[GroupchatUist]> rooms2: [];
    in-out property <[MessageUist]> messages2: [];
    
    private property <bool> stkrlui2: true;
    private property <string> curpage: "none";
    private property <string> lastpage: "none";

    callback justrunafunc();

    columns: ["111", "222", "333"];
    messages: [["ffff"],["gggggg"], ["hhhhhhh"], ["iiiiiii"], ["jjjjjjjj"], ["kkkkkkkk"], ["lllllllll"],["mmmmmmmm"],["nnnnnnnnnn"],["gggggg"], ["hhhhhhh"], ["iiiiiii"], ["jjjjjjjj"], ["kkkkkkkk"], ["lllllllll"],["mmmmmmmm"],["nnnnnnnnnn"],["gggggg"], ["hhhhhhh"], ["iiiiiii"], ["jjjjjjjj"], ["kkkkkkkk"], ["lllllllll"],["mmmmmmmm"],["nnnnnnnnnn"],["gggggg"], ["hhhhhhh"], ["iiiiiii"], ["jjjjjjjj"], ["kkkkkkkk"], ["lllllllll"],["mmmmmmmm"],["nnnnnnnnnn"]];

    padding: 0px;
    // width: 800px; // android上不能设置
    // height: 600px;
    VerticalLayout {
        toolbar := HorizontalLayout{
            Button {text: "jjj";}
            Button {text: "jjj";}
            HSpacer {}
            Button {text: "RLUI";
            clicked => {
                curpage = "rlstui2";
                switchstack();
            }

        }

        Button {text: "MSGLST";
            clicked => {
                curpage = "msglst";
                switchstack();
            }
        }
        Button {text: "ABUI";
        clicked => {
            curpage = "aboutui";
            switchstack();
        }
        }
        }
    
    lo1 := HorizontalLayout {
        padding: 1px;

        if varfn.isandroid != 1:  HorizontalLayout {
            rlstui := RoomListAndUserInfoui{
                rooms2 <=> root.rooms2;
            }
        // if varfn.isandroid() != 1:  
           splt1 := Splitter {
            // x: parent.width - self.width;
            // height: 100%;

            // seems slow
            moved => {
                // self.x = min(parent.width - self.width, max(400px, self.x + self.mouse-x - self.pressed-x));
                self.x = min(lo1.width - self.width, max(100px, self.x + self.mouse-x - self.pressed-x));
                // tw.x = self.x;
                // tw.width = lo1.width - self.x;
                // rlstui.width = self.x;
            }

            init => {
                // lo1.width = (root.width*1)/3;
                
            }
        }
    }

    // stack widget
    stkwin := Rectangle {
        min-width: 150px;
        min-height: 50px;
        // width: parent.width - lo1.width;
        horizontal-stretch: 4; // 重要，可以区分比例
        vertical-stretch: 1;
        // background: #bb7f42;
        // preferred-width: 300px;

        // TextInput {text: "iiiiiiiii";}
        // StandardButton {kind: cancel;}
        // GroupBox {
        //     visible: false;
        //     CheckBox {text: "chkkk";}
        // }

        
        // if varfn.isandroid() == 1:  RoomListAndUserInfoui{}
        if varfn.isandroid == 1: RoomListAndUserInfoui{
            rooms2 <=> root.rooms2;
            // visible <=> root.stkrlui2;
            states [
                s1 when root.stkrlui2 == true : {
                    visible: true;
                } s2 when root.stkrlui2 == false : {
                    visible: false;
                }
            ]    
        }

        // right message list
        rgtlo:= VerticalLayout {
            visible: varfn.isandroid==0;
            padding: 0px;
            

            // MessageListHeadui {
            //     msgcnt: messages.length;
            // }
            ListView {
                padding: 0px;
            

                for v in root.messages : 
                MessageListItemui {
                    msgchan:  v[0];
                }
                
            }
            MessageListTailui {}
        }

        aboutui := GroupBox{
            visible: false;
            Button {text: "123";}
        }
        init => {
            debug("stkwin init...", varfn.isandroid)
        }
    }

        
    }

    stsbar := HorizontalLayout{
        Button {text: "jjj";}
        Button {text: "jjj";}
        Button {text: "jjj";}
        HSpacer {}
        Button {text: "jjj";}
        Button {text: "jjj";}
    }
    }

    states [
        onosandroid when varfn.isandroid == 1 : {
            // tw.current-index: 0;
        }
        onpc when varfn.isandroid != 1 : {
            // tw.current-index: 1;
        }

        // showaboutui when curpage == "aboutui" : {
        //     aboutui.visible : true;
        // }
    ]

    // cannot
    // private property <[Element]> name: [rgtlo];
    function  hideallelems() {
            // if rlstui2.visible == true {
            //     rlstui2.visible = false;
            // }
        if rgtlo.visible == true {
            rgtlo.visible = false;
            lastpage = "msglst";
        }
        if stkrlui2 == true {
            stkrlui2 = false;
            lastpage = "rlstui2";
        }


        if aboutui.visible == true {
            aboutui.visible = false;
            lastpage = "aboutui";
        }
    }
    function  switchstack() {
        hideallelems();
        debug("curpage", curpage, lastpage);
        
        // stkrlui2 = true;
        if stkrlui2 == true {
            // rlstui2.visible = true;
        }else{
            // rgtlo.visible = true;
        }
        if curpage == "msglst" {
            rgtlo.visible = true;
            //               rlstui2
        } else if curpage == "rlstui2" {
            if varfn.isandroid == 1 {
                stkrlui2 = true;
            }else{
                debug("want show rlstui2, but not android");
                // curpage = lastpage;
                // switchstack();
            }
        }else if curpage == "aboutui" {
            aboutui.visible = true;
        } else {

        }
    }

    function trysplitrate() {
        
    }

    // 这个最先调用
    init => {
        debug("AppWindow inited,"+varfn.isandroid);
        // if varfn.isandroid() != 1 {
        //     tw.current-index = 1;
        // //     tb0.opacity = 1;
        // //     tb0.visible = false;
        // }else{
        //     tw.current-index = 0;
        // }
        // if varfn.isandroid() == 1 {
        //     stkrlui2 = false;
        //     stkrlui2 = true;
        //     curpage = "rlstui2";
        // }else{
        //     stkrlui2 = false;
        //     curpage = "msglst";
        // }
        // debug("hhhhhhee", curpage, varfn.isandroid());
        // // if varfn.isandroid() == 1 {

        // switchstack();
        // trysplitrate();
        // stkwin.width = root.width - lo1.width;
        // stkwin.width = 300px;

    }
    
}

