
import { Button, VerticalBox, GridBox, CheckBox, ComboBox, Switch, Spinner, LineEdit, ListView, AboutSlint, ProgressIndicator, SpinBox, HorizontalBox, StandardListView,GroupBox, TabWidget } from "std-widgets.slint";


component mytabwidget inherits TabWidget {
    
}

component stackwidget inherits Rectangle {
    in-out property <int> curridx : 0;
    

    gb1 := GroupBox {
            visible: true;
            Text {text: "ingrpbox";}
        }

    le1 := LineEdit {placeholder-text: "hehehhe";}

    function setcurridx2(idx : int) {
        if idx == 0 {
            gb1.visible = true;
            le1.visible = false;
        }else if idx==1{
            gb1.visible = false;
            le1.visible = true;
        }
    }

    states [
        child0 when curridx==0:{
            
        }
    ]

    // states [
    //     child0 when curridx==0 : {
    //         gb1.visible: true;
    //         le1.visible: false;
    //     }
    //     child1 when curridx==1 : {
    //         gb1.visible: false;
    //         le1.visible: true;
    //     }
    // ]
}



// component testiii {
//     tw := TabWidget {
//         padding: 1px;
//         visible: false;
//         // y: root.y - 50px;

//         // Tab {stackwidget{}}

//         tb0 := Tab {
//             padding: 1px;
//             title: "000";

//             VerticalLayout {
//                 padding: 1px;
//             // LineEdit {}
//             // LineEdit {}
//                 // if varfn.isandroid() == 1:  RoomListAndUserInfoui{}
//                 RoomListAndUserInfoui{}
//             }
//         }
//         Tab {
//             title: "111";
//             // message list 主窗口
//             VerticalLayout {
//                 padding: 0px;
//                 MessageListHeadui {
//                     // msgcnt: messages.length;
//                 }
//                 ListView {
//                     padding: 0px;
//                     // for v in root.messages : 
//                     // MessageListItemui {
//                     //     msgchan:  v[0];
//                     // }
                    
//                 }
//                 MessageListTailui {}
//             }
//         }
//         Tab {
//             title: "222";
//             Button {text: "sssss";}
//         }
//         // Tab {
//         //     title: "333";
//         //     Button {text: "sssss";}
//         // }
        
//     }

// }



export component AppWindow2 inherits Window {
    in-out property<int> counter: 42;
    in-out property<string> fdname: "nammm";

    in property <[string]> columns;
    in property <[[string]]> values;

    callback request-increase-value();
    callback justrunafunc();

    VerticalBox {
        // UserInfo {}

        ListView {
            for r in  root.values :  LineEdit{}
        }
        

        Text {
            text: "Counter: \{root.counter}";
        }
        Button {
            text: "Increase value";
            clicked => {
                root.request-increase-value();
            }
        }
        Text {
            text: "Counter: \{root.fdname}";
        }
        Button {
            text: "justrunafunc";
            clicked => {
                root.justrunafunc();
            }
        }
        Path { }
        ListView { }


        GridBox {
            
            CheckBox {
                text: "CheckBox";
            }
            ComboBox {
                model: ["first", "second", "third"];
            }
            Button {
                text: "Button";
            }
            Switch {
                text: "Switch";
            }
            Spinner { }
            LineEdit {
                text: "LineEdi拖拖拉拉";
            }
   

            ProgressIndicator { }
        }

        // splitter1 := Splitter {
        //     x: root.width - self.width;
        //     height: 100%;
    
        //     moved => {
        //         self.x = min(root.width - self.width, max(400px, self.x + self.mouse-x - self.pressed-x));
        //     }
        // }
    }
    
}
